name: DNS Range Scanner

on:
  workflow_dispatch:
    inputs:
      domain:
        description: 'Domain to resolve'
        required: true
        default: 'google.com'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build and Run Scanner
        run: |
          dotnet build
          dotnet run
        env:
          INPUT_DOMAIN: ${{ github.event.inputs.domain }}
      - name: Upload log
        uses: actions/upload-artifact@v4
        with:
          name: scan-log
          path: scan_output.txt
